spring:
  config:
    import: aws-parameterstore:/commerce-payment-system-v2/prod/
  cloud:
    aws:
      region:
        static: ap-northeast-2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}

server:
  forward-headers-strategy: framework

logging:
  level:
    org.hibernate.SQL: WARN
    io.github.spartateam6.commercepaymentsystem.global.logging.ControllerLoggingAspect: WARN